// Code generated by gen (postgres typed-unsupported shell); DO NOT EDIT.

package sqlite

import (
	"context"
	"github.com/steveyegge/beads/internal/storage"
	"github.com/steveyegge/beads/internal/types"
	"time"
)

// unsupportedDoltStorage is the generated typed-unsupported shell for storage.DoltStorage.
// Every method returns *storage.ErrUnsupported; embed it and override the
// real slice. DO NOT hand-edit — regenerate with `go generate ./...`.
type unsupportedDoltStorage struct{}

func (unsupportedDoltStorage) GetIssueByExternalRef(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("GetIssueByExternalRef")
	return
}

func (unsupportedDoltStorage) GetAllEventsSince(_ context.Context, _ time.Time) (_ []*types.Event, err error) {
	err = errUnsupported("GetAllEventsSince")
	return
}

func (unsupportedDoltStorage) IterAllEventsSince(_ context.Context, _ time.Time) (_ storage.Iter[types.Event], err error) {
	err = errUnsupported("IterAllEventsSince")
	return
}

func (unsupportedDoltStorage) GetStatistics(_ context.Context) (_ *types.Statistics, err error) {
	err = errUnsupported("GetStatistics")
	return
}

func (unsupportedDoltStorage) MergeSlotCreate(_ context.Context, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("MergeSlotCreate")
	return
}

func (unsupportedDoltStorage) MergeSlotCheck(_ context.Context) (_ *storage.MergeSlotStatus, err error) {
	err = errUnsupported("MergeSlotCheck")
	return
}

func (unsupportedDoltStorage) MergeSlotAcquire(_ context.Context, _ string, _ string, _ bool) (_ *storage.MergeSlotResult, err error) {
	err = errUnsupported("MergeSlotAcquire")
	return
}

func (unsupportedDoltStorage) MergeSlotRelease(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("MergeSlotRelease")
	return
}

func (unsupportedDoltStorage) SlotSet(_ context.Context, _ string, _ string, _ string, _ string) (err error) {
	err = errUnsupported("SlotSet")
	return
}

func (unsupportedDoltStorage) SlotGet(_ context.Context, _ string, _ string) (_ string, err error) {
	err = errUnsupported("SlotGet")
	return
}

func (unsupportedDoltStorage) SlotClear(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("SlotClear")
	return
}

func (unsupportedDoltStorage) Branch(_ context.Context, _ string) (err error) {
	err = errUnsupported("Branch")
	return
}

func (unsupportedDoltStorage) Checkout(_ context.Context, _ string) (err error) {
	err = errUnsupported("Checkout")
	return
}

func (unsupportedDoltStorage) CurrentBranch(_ context.Context) (_ string, err error) {
	err = errUnsupported("CurrentBranch")
	return
}

func (unsupportedDoltStorage) DeleteBranch(_ context.Context, _ string) (err error) {
	err = errUnsupported("DeleteBranch")
	return
}

func (unsupportedDoltStorage) ListBranches(_ context.Context) (_ []string, err error) {
	err = errUnsupported("ListBranches")
	return
}

func (unsupportedDoltStorage) CommitExists(_ context.Context, _ string) (_ bool, err error) {
	err = errUnsupported("CommitExists")
	return
}

func (unsupportedDoltStorage) GetCurrentCommit(_ context.Context) (_ string, err error) {
	err = errUnsupported("GetCurrentCommit")
	return
}

func (unsupportedDoltStorage) Status(_ context.Context) (_ *storage.Status, err error) {
	err = errUnsupported("Status")
	return
}

func (unsupportedDoltStorage) Log(_ context.Context, _ int) (_ []storage.CommitInfo, err error) {
	err = errUnsupported("Log")
	return
}

func (unsupportedDoltStorage) Merge(_ context.Context, _ string) (_ []storage.Conflict, err error) {
	err = errUnsupported("Merge")
	return
}

func (unsupportedDoltStorage) GetConflicts(_ context.Context) (_ []storage.Conflict, err error) {
	err = errUnsupported("GetConflicts")
	return
}

func (unsupportedDoltStorage) ResolveConflicts(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("ResolveConflicts")
	return
}

func (unsupportedDoltStorage) History(_ context.Context, _ string) (_ []*storage.HistoryEntry, err error) {
	err = errUnsupported("History")
	return
}

func (unsupportedDoltStorage) AsOf(_ context.Context, _ string, _ string) (_ *types.Issue, err error) {
	err = errUnsupported("AsOf")
	return
}

func (unsupportedDoltStorage) Diff(_ context.Context, _ string, _ string) (_ []*storage.DiffEntry, err error) {
	err = errUnsupported("Diff")
	return
}

func (unsupportedDoltStorage) AddRemote(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("AddRemote")
	return
}

func (unsupportedDoltStorage) RemoveRemote(_ context.Context, _ string) (err error) {
	err = errUnsupported("RemoveRemote")
	return
}

func (unsupportedDoltStorage) HasRemote(_ context.Context, _ string) (_ bool, err error) {
	err = errUnsupported("HasRemote")
	return
}

func (unsupportedDoltStorage) ListRemotes(_ context.Context) (_ []storage.RemoteInfo, err error) {
	err = errUnsupported("ListRemotes")
	return
}

func (unsupportedDoltStorage) Push(_ context.Context) (err error) {
	err = errUnsupported("Push")
	return
}

func (unsupportedDoltStorage) Pull(_ context.Context) (err error) {
	err = errUnsupported("Pull")
	return
}

func (unsupportedDoltStorage) ForcePush(_ context.Context) (err error) {
	err = errUnsupported("ForcePush")
	return
}

func (unsupportedDoltStorage) PushRemote(_ context.Context, _ string, _ bool) (err error) {
	err = errUnsupported("PushRemote")
	return
}

func (unsupportedDoltStorage) PullRemote(_ context.Context, _ string) (err error) {
	err = errUnsupported("PullRemote")
	return
}

func (unsupportedDoltStorage) Fetch(_ context.Context, _ string) (err error) {
	err = errUnsupported("Fetch")
	return
}

func (unsupportedDoltStorage) PushTo(_ context.Context, _ string) (err error) {
	err = errUnsupported("PushTo")
	return
}

func (unsupportedDoltStorage) PullFrom(_ context.Context, _ string) (_ []storage.Conflict, err error) {
	err = errUnsupported("PullFrom")
	return
}

func (unsupportedDoltStorage) Sync(_ context.Context, _ string, _ string) (_ *storage.SyncResult, err error) {
	err = errUnsupported("Sync")
	return
}

func (unsupportedDoltStorage) SyncStatus(_ context.Context, _ string) (_ *storage.SyncStatus, err error) {
	err = errUnsupported("SyncStatus")
	return
}

func (unsupportedDoltStorage) AddFederationPeer(_ context.Context, _ *storage.FederationPeer) (err error) {
	err = errUnsupported("AddFederationPeer")
	return
}

func (unsupportedDoltStorage) GetFederationPeer(_ context.Context, _ string) (_ *storage.FederationPeer, err error) {
	err = errUnsupported("GetFederationPeer")
	return
}

func (unsupportedDoltStorage) ListFederationPeers(_ context.Context) (_ []*storage.FederationPeer, err error) {
	err = errUnsupported("ListFederationPeers")
	return
}

func (unsupportedDoltStorage) RemoveFederationPeer(_ context.Context, _ string) (err error) {
	err = errUnsupported("RemoveFederationPeer")
	return
}

func (unsupportedDoltStorage) CreateIssuesWithFullOptions(_ context.Context, _ []*types.Issue, _ string, _ storage.BatchCreateOptions) (err error) {
	err = errUnsupported("CreateIssuesWithFullOptions")
	return
}

func (unsupportedDoltStorage) DeleteIssuesBySourceRepo(_ context.Context, _ string) (_ int, err error) {
	err = errUnsupported("DeleteIssuesBySourceRepo")
	return
}

func (unsupportedDoltStorage) UpdateIssueID(_ context.Context, _ string, _ string, _ *types.Issue, _ string) (err error) {
	err = errUnsupported("UpdateIssueID")
	return
}

func (unsupportedDoltStorage) PromoteFromEphemeral(_ context.Context, _ string, _ string) (err error) {
	err = errUnsupported("PromoteFromEphemeral")
	return
}

func (unsupportedDoltStorage) GetAllDependencyRecords(_ context.Context) (_ map[string][]*types.Dependency, err error) {
	err = errUnsupported("GetAllDependencyRecords")
	return
}

func (unsupportedDoltStorage) FindWispDependentsRecursive(_ context.Context, _ []string) (_ map[string]bool, err error) {
	err = errUnsupported("FindWispDependentsRecursive")
	return
}

func (unsupportedDoltStorage) IterAllDependencyRecords(_ context.Context) (_ storage.Iter[types.Dependency], err error) {
	err = errUnsupported("IterAllDependencyRecords")
	return
}

func (unsupportedDoltStorage) CountDependentsByStatus(_ context.Context, _ string, _ types.Status) (_ int64, err error) {
	err = errUnsupported("CountDependentsByStatus")
	return
}

func (unsupportedDoltStorage) AddComment(_ context.Context, _ string, _ string, _ string) (err error) {
	err = errUnsupported("AddComment")
	return
}

func (unsupportedDoltStorage) ImportIssueComment(_ context.Context, _ string, _ string, _ string, _ time.Time) (_ *types.Comment, err error) {
	err = errUnsupported("ImportIssueComment")
	return
}

func (unsupportedDoltStorage) CheckEligibility(_ context.Context, _ string, _ int) (_ bool, _ string, err error) {
	err = errUnsupported("CheckEligibility")
	return
}

func (unsupportedDoltStorage) ApplyCompaction(_ context.Context, _ string, _ int, _ int, _ int, _ string) (err error) {
	err = errUnsupported("ApplyCompaction")
	return
}

func (unsupportedDoltStorage) GetTier1Candidates(_ context.Context) (_ []*types.CompactionCandidate, err error) {
	err = errUnsupported("GetTier1Candidates")
	return
}

func (unsupportedDoltStorage) GetTier2Candidates(_ context.Context) (_ []*types.CompactionCandidate, err error) {
	err = errUnsupported("GetTier2Candidates")
	return
}

func (unsupportedDoltStorage) SnapshotIssue(_ context.Context, _ string, _ int) (err error) {
	err = errUnsupported("SnapshotIssue")
	return
}

func (unsupportedDoltStorage) GetCompactionSnapshot(_ context.Context, _ string) (_ *types.IssueSnapshot, err error) {
	err = errUnsupported("GetCompactionSnapshot")
	return
}

func (unsupportedDoltStorage) RestoreFromSnapshot(_ context.Context, _ string) (_ *types.IssueSnapshot, err error) {
	err = errUnsupported("RestoreFromSnapshot")
	return
}

func (unsupportedDoltStorage) GetRepoMtime(_ context.Context, _ string) (_ int64, err error) {
	err = errUnsupported("GetRepoMtime")
	return
}

func (unsupportedDoltStorage) SetRepoMtime(_ context.Context, _ string, _ string, _ int64) (err error) {
	err = errUnsupported("SetRepoMtime")
	return
}

func (unsupportedDoltStorage) ClearRepoMtime(_ context.Context, _ string) (err error) {
	err = errUnsupported("ClearRepoMtime")
	return
}

func (unsupportedDoltStorage) GetMoleculeProgress(_ context.Context, _ string) (_ *types.MoleculeProgressStats, err error) {
	err = errUnsupported("GetMoleculeProgress")
	return
}

func (unsupportedDoltStorage) GetMoleculeLastActivity(_ context.Context, _ string) (_ *types.MoleculeLastActivity, err error) {
	err = errUnsupported("GetMoleculeLastActivity")
	return
}

func (unsupportedDoltStorage) GetStaleIssues(_ context.Context, _ types.StaleFilter) (_ []*types.Issue, err error) {
	err = errUnsupported("GetStaleIssues")
	return
}

// NOTE: partial shell (77 methods skipped); the embedding composite must assert storage.DoltStorage itself.
