//go:build ignore

// Command generate writes the explicit unsupported backend method shell used
// by this evidence fixture. It imports only the public backend package; the
// generated source is checked in and is never regenerated by the compile test.
package main

import (
	"fmt"
	"go/format"
	"os"
	"reflect"
	"strings"

	"github.com/steveyegge/beads/backend"
)

func main() {
	contract := reflect.TypeOf((*backend.DoltStorage)(nil)).Elem()
	var methods strings.Builder
	for i := range contract.NumMethod() {
		method := contract.Method(i)
		signature := publicType(strings.TrimPrefix(method.Type.String(), "func"))
		fmt.Fprintf(&methods, "func (*Store) %s%s {", method.Name, signature)
		if method.Type.NumOut() == 0 {
			methods.WriteString(" return }")
		} else {
			methods.WriteString(" return ")
			for j := range method.Type.NumOut() {
				if j > 0 {
					methods.WriteString(", ")
				}
				methods.WriteString(zeroValue(method.Name, method.Type.Out(j)))
			}
			methods.WriteString(" }")
		}
		methods.WriteByte('\n')
	}

	source := `// Code generated by go run generate.go; DO NOT EDIT.

package externalbackend

import (
	"context"
	"encoding/json"
	"time"

	"github.com/steveyegge/beads/backend"
	"github.com/steveyegge/beads/issueops"
	"github.com/steveyegge/beads/memoryops"
)

// Store is a concrete, deliberately unsupported external backend. Every
// backend method is declared here: Store does not inherit the contract by
// anonymously embedding backend.DoltStorage.
type Store struct{}

var _ backend.DoltStorage = (*Store)(nil)

func unsupported(op string) error {
	return &backend.ErrUnsupported{Op: op, Backend: "a1-external-fixture"}
}

` + methods.String()

	formatted, err := format.Source([]byte(source))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("unsupported_store_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func publicType(value string) string {
	// reflect includes a package's full import path for named generic
	// arguments, while ordinary named values use only the package name.
	value = strings.ReplaceAll(value, "github.com/steveyegge/beads/internal/storage.Status", "backend.VCStatus")
	value = strings.ReplaceAll(value, "github.com/steveyegge/beads/internal/storage.", "backend.")
	value = strings.ReplaceAll(value, "github.com/steveyegge/beads/internal/types.", "backend.")
	value = strings.ReplaceAll(value, "storage.Status", "backend.VCStatus")
	value = strings.ReplaceAll(value, "storage.", "backend.")
	value = strings.ReplaceAll(value, "types.", "backend.")
	return value
}

func zeroValue(method string, value reflect.Type) string {
	errorType := reflect.TypeOf((*error)(nil)).Elem()
	if value.Implements(errorType) {
		return fmt.Sprintf("unsupported(%q)", method)
	}
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return "nil"
	case reflect.Bool:
		return "false"
	case reflect.String:
		return `""`
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Uintptr, reflect.Float32, reflect.Float64, reflect.Complex64, reflect.Complex128:
		return "0"
	case reflect.Array, reflect.Struct:
		return publicType(value.String()) + "{}"
	default:
		panic(fmt.Sprintf("no zero value for %s result %s", method, value))
	}
}
