// Code generated by go run generate.go; DO NOT EDIT.

package externalbackend

import (
	"context"
	"encoding/json"
	"time"

	"github.com/steveyegge/beads/backend"
	"github.com/steveyegge/beads/issueops"
	"github.com/steveyegge/beads/memoryops"
)

// Store is a concrete, deliberately unsupported external backend. Every
// backend method is declared here: Store does not inherit the contract by
// anonymously embedding backend.DoltStorage.
type Store struct{}

var _ backend.DoltStorage = (*Store)(nil)

func unsupported(op string) error {
	return &backend.ErrUnsupported{Op: op, Backend: "a1-external-fixture"}
}

func (*Store) AddComment(context.Context, string, string, string) error {
	return unsupported("AddComment")
}
func (*Store) AddDependency(context.Context, *backend.Dependency, string) error {
	return unsupported("AddDependency")
}
func (*Store) AddDependencyWithOptions(context.Context, *backend.Dependency, string, backend.DependencyAddOptions) error {
	return unsupported("AddDependencyWithOptions")
}
func (*Store) AddFederationPeer(context.Context, *backend.FederationPeer) error {
	return unsupported("AddFederationPeer")
}
func (*Store) AddIssueComment(context.Context, string, string, string) (*backend.Comment, error) {
	return nil, unsupported("AddIssueComment")
}
func (*Store) AddLabel(context.Context, string, string, string) error { return unsupported("AddLabel") }
func (*Store) AddRemote(context.Context, string, string) error        { return unsupported("AddRemote") }
func (*Store) ApplyCompaction(context.Context, string, int, int, int, string) error {
	return unsupported("ApplyCompaction")
}
func (*Store) AsOf(context.Context, string, string) (*backend.Issue, error) {
	return nil, unsupported("AsOf")
}
func (*Store) BatchCloser() (issueops.BatchCloser, error)   { return nil, unsupported("BatchCloser") }
func (*Store) BatchCreator() (issueops.BatchCreator, error) { return nil, unsupported("BatchCreator") }
func (*Store) BlockingAnnotator() (issueops.BlockingAnnotator, error) {
	return nil, unsupported("BlockingAnnotator")
}
func (*Store) Bootstrapper() (issueops.Bootstrapper, error) { return nil, unsupported("Bootstrapper") }
func (*Store) Branch(context.Context, string) error         { return unsupported("Branch") }
func (*Store) CheckEligibility(context.Context, string, int) (bool, string, error) {
	return false, "", unsupported("CheckEligibility")
}
func (*Store) Checkout(context.Context, string) error           { return unsupported("Checkout") }
func (*Store) ClaimIssue(context.Context, string, string) error { return unsupported("ClaimIssue") }
func (*Store) ClaimReadyIssue(context.Context, backend.WorkFilter, string) (*backend.Issue, error) {
	return nil, unsupported("ClaimReadyIssue")
}
func (*Store) ClearRepoMtime(context.Context, string) error { return unsupported("ClearRepoMtime") }
func (*Store) Close() error                                 { return unsupported("Close") }
func (*Store) CloseIssue(context.Context, string, string, string, string) error {
	return unsupported("CloseIssue")
}
func (*Store) CloseIssueChecked(context.Context, string, string, backend.CloseIssueOptions) (backend.CloseIssueResult, error) {
	return backend.CloseIssueResult{}, unsupported("CloseIssueChecked")
}
func (*Store) Commenter() (issueops.Commenter, error) { return nil, unsupported("Commenter") }
func (*Store) Commit(context.Context, string) error   { return unsupported("Commit") }
func (*Store) CommitExists(context.Context, string) (bool, error) {
	return false, unsupported("CommitExists")
}
func (*Store) CommitMergeResolution(context.Context, string) error {
	return unsupported("CommitMergeResolution")
}
func (*Store) CommitPending(context.Context, string) (bool, error) {
	return false, unsupported("CommitPending")
}
func (*Store) CommitWithConfig(context.Context, string) error { return unsupported("CommitWithConfig") }
func (*Store) CountDependencies(context.Context, string) (int64, error) {
	return 0, unsupported("CountDependencies")
}
func (*Store) CountDependentRecords(context.Context, string, string) (int, error) {
	return 0, unsupported("CountDependentRecords")
}
func (*Store) CountDependents(context.Context, string) (int64, error) {
	return 0, unsupported("CountDependents")
}
func (*Store) CountDependentsByStatus(context.Context, string, backend.Status) (int64, error) {
	return 0, unsupported("CountDependentsByStatus")
}
func (*Store) CountEvents(context.Context, string, int) (int64, error) {
	return 0, unsupported("CountEvents")
}
func (*Store) CountIssueComments(context.Context, string) (int64, error) {
	return 0, unsupported("CountIssueComments")
}
func (*Store) CountIssues(context.Context, string, backend.IssueFilter) (int64, error) {
	return 0, unsupported("CountIssues")
}
func (*Store) CountIssuesByGroup(context.Context, backend.IssueFilter, string) (map[string]int, error) {
	return nil, unsupported("CountIssuesByGroup")
}
func (*Store) Counter() (issueops.Counter, error) { return nil, unsupported("Counter") }
func (*Store) CreateIssue(context.Context, *backend.Issue, string) error {
	return unsupported("CreateIssue")
}
func (*Store) CreateIssues(context.Context, []*backend.Issue, string) error {
	return unsupported("CreateIssues")
}
func (*Store) CreateIssuesWithFullOptions(context.Context, []*backend.Issue, string, backend.BatchCreateOptions) error {
	return unsupported("CreateIssuesWithFullOptions")
}
func (*Store) CurrentBranch(context.Context) (string, error) { return "", unsupported("CurrentBranch") }
func (*Store) CycleDetector() (issueops.CycleDetector, error) {
	return nil, unsupported("CycleDetector")
}
func (*Store) DeleteBranch(context.Context, string) error { return unsupported("DeleteBranch") }
func (*Store) DeleteConfig(context.Context, string) error { return unsupported("DeleteConfig") }
func (*Store) DeleteIssue(context.Context, string) error  { return unsupported("DeleteIssue") }
func (*Store) DeleteIssues(context.Context, []string, bool, bool, bool) (*backend.DeleteIssuesResult, error) {
	return nil, unsupported("DeleteIssues")
}
func (*Store) DeleteIssuesBySourceRepo(context.Context, string) (int, error) {
	return 0, unsupported("DeleteIssuesBySourceRepo")
}
func (*Store) Deleter() (issueops.Deleter, error) { return nil, unsupported("Deleter") }
func (*Store) DependencyEditor() (issueops.DependencyEditor, error) {
	return nil, unsupported("DependencyEditor")
}
func (*Store) DetectCycles(context.Context) ([][]*backend.Issue, error) {
	return nil, unsupported("DetectCycles")
}
func (*Store) Diff(context.Context, string, string) ([]*backend.DiffEntry, error) {
	return nil, unsupported("Diff")
}
func (*Store) EdgeReader() (issueops.EdgeReader, error) { return nil, unsupported("EdgeReader") }
func (*Store) EventsSince(context.Context, backend.EventCursor, string, int) ([]*backend.Event, error) {
	return nil, unsupported("EventsSince")
}
func (*Store) Fetch(context.Context, string) error { return unsupported("Fetch") }
func (*Store) FindWispDependentsRecursive(context.Context, []string) (map[string]bool, error) {
	return nil, unsupported("FindWispDependentsRecursive")
}
func (*Store) ForcePush(context.Context) error { return unsupported("ForcePush") }
func (*Store) GetAllConfig(context.Context) (map[string]string, error) {
	return nil, unsupported("GetAllConfig")
}
func (*Store) GetAllDependencyRecords(context.Context) (map[string][]*backend.Dependency, error) {
	return nil, unsupported("GetAllDependencyRecords")
}
func (*Store) GetAllEventsSince(context.Context, time.Time) ([]*backend.Event, error) {
	return nil, unsupported("GetAllEventsSince")
}
func (*Store) GetBlockedIssues(context.Context, backend.WorkFilter) ([]*backend.BlockedIssue, error) {
	return nil, unsupported("GetBlockedIssues")
}
func (*Store) GetBlockingInfoForIssues(context.Context, []string) (map[string][]string, map[string][]string, map[string]string, error) {
	return nil, nil, nil, unsupported("GetBlockingInfoForIssues")
}
func (*Store) GetCommentCounts(context.Context, []string) (map[string]int, error) {
	return nil, unsupported("GetCommentCounts")
}
func (*Store) GetCommentsForIssues(context.Context, []string) (map[string][]*backend.Comment, error) {
	return nil, unsupported("GetCommentsForIssues")
}
func (*Store) GetCompactionSnapshot(context.Context, string) (*backend.IssueSnapshot, error) {
	return nil, unsupported("GetCompactionSnapshot")
}
func (*Store) GetConfig(context.Context, string) (string, error) { return "", unsupported("GetConfig") }
func (*Store) GetConflicts(context.Context) ([]backend.Conflict, error) {
	return nil, unsupported("GetConflicts")
}
func (*Store) GetCurrentCommit(context.Context) (string, error) {
	return "", unsupported("GetCurrentCommit")
}
func (*Store) GetCustomStatuses(context.Context) ([]string, error) {
	return nil, unsupported("GetCustomStatuses")
}
func (*Store) GetCustomStatusesDetailed(context.Context) ([]backend.CustomStatus, error) {
	return nil, unsupported("GetCustomStatusesDetailed")
}
func (*Store) GetCustomTypes(context.Context) ([]string, error) {
	return nil, unsupported("GetCustomTypes")
}
func (*Store) GetDependencies(context.Context, string) ([]*backend.Issue, error) {
	return nil, unsupported("GetDependencies")
}
func (*Store) GetDependenciesWithMetadata(context.Context, string) ([]*backend.IssueWithDependencyMetadata, error) {
	return nil, unsupported("GetDependenciesWithMetadata")
}
func (*Store) GetDependencyCounts(context.Context, []string) (map[string]*backend.DependencyCounts, error) {
	return nil, unsupported("GetDependencyCounts")
}
func (*Store) GetDependencyRecords(context.Context, string) ([]*backend.Dependency, error) {
	return nil, unsupported("GetDependencyRecords")
}
func (*Store) GetDependencyRecordsForIssues(context.Context, []string) (map[string][]*backend.Dependency, error) {
	return nil, unsupported("GetDependencyRecordsForIssues")
}
func (*Store) GetDependencyTree(context.Context, string, int, bool, bool) ([]*backend.TreeNode, error) {
	return nil, unsupported("GetDependencyTree")
}
func (*Store) GetDependentRecords(context.Context, string, string, int, string) ([]*backend.Dependency, error) {
	return nil, unsupported("GetDependentRecords")
}
func (*Store) GetDependentRecordsForIssues(context.Context, []string) (map[string][]*backend.Dependency, error) {
	return nil, unsupported("GetDependentRecordsForIssues")
}
func (*Store) GetDependents(context.Context, string) ([]*backend.Issue, error) {
	return nil, unsupported("GetDependents")
}
func (*Store) GetDependentsWithMetadata(context.Context, string) ([]*backend.IssueWithDependencyMetadata, error) {
	return nil, unsupported("GetDependentsWithMetadata")
}
func (*Store) GetEpicsEligibleForClosure(context.Context) ([]*backend.EpicStatus, error) {
	return nil, unsupported("GetEpicsEligibleForClosure")
}
func (*Store) GetEvents(context.Context, string, int) ([]*backend.Event, error) {
	return nil, unsupported("GetEvents")
}
func (*Store) GetFederationPeer(context.Context, string) (*backend.FederationPeer, error) {
	return nil, unsupported("GetFederationPeer")
}
func (*Store) GetInfraTypes(context.Context) map[string]bool { return nil }
func (*Store) GetIssue(context.Context, string) (*backend.Issue, error) {
	return nil, unsupported("GetIssue")
}
func (*Store) GetIssueByExternalRef(context.Context, string) (*backend.Issue, error) {
	return nil, unsupported("GetIssueByExternalRef")
}
func (*Store) GetIssueComments(context.Context, string) ([]*backend.Comment, error) {
	return nil, unsupported("GetIssueComments")
}
func (*Store) GetIssueCommentsPage(context.Context, string, backend.CommentPageCursor, int) ([]*backend.Comment, error) {
	return nil, unsupported("GetIssueCommentsPage")
}
func (*Store) GetIssuesByIDs(context.Context, []string) ([]*backend.Issue, error) {
	return nil, unsupported("GetIssuesByIDs")
}
func (*Store) GetIssuesByLabel(context.Context, string) ([]*backend.Issue, error) {
	return nil, unsupported("GetIssuesByLabel")
}
func (*Store) GetLabels(context.Context, string) ([]string, error) {
	return nil, unsupported("GetLabels")
}
func (*Store) GetLabelsForIssues(context.Context, []string) (map[string][]string, error) {
	return nil, unsupported("GetLabelsForIssues")
}
func (*Store) GetLocalMetadata(context.Context, string) (string, error) {
	return "", unsupported("GetLocalMetadata")
}
func (*Store) GetMetadata(context.Context, string) (string, error) {
	return "", unsupported("GetMetadata")
}
func (*Store) GetMoleculeLastActivity(context.Context, string) (*backend.MoleculeLastActivity, error) {
	return nil, unsupported("GetMoleculeLastActivity")
}
func (*Store) GetMoleculeProgress(context.Context, string) (*backend.MoleculeProgressStats, error) {
	return nil, unsupported("GetMoleculeProgress")
}
func (*Store) GetNewlyUnblockedByClose(context.Context, string) ([]*backend.Issue, error) {
	return nil, unsupported("GetNewlyUnblockedByClose")
}
func (*Store) GetNextChildID(context.Context, string) (string, error) {
	return "", unsupported("GetNextChildID")
}
func (*Store) GetProvenanceByRef(context.Context, string) ([]backend.ProvenanceEvent, error) {
	return nil, unsupported("GetProvenanceByRef")
}
func (*Store) GetProvenanceEvents(context.Context, string, string) ([]backend.ProvenanceEvent, error) {
	return nil, unsupported("GetProvenanceEvents")
}
func (*Store) GetReadyWork(context.Context, backend.WorkFilter) ([]*backend.Issue, error) {
	return nil, unsupported("GetReadyWork")
}
func (*Store) GetReadyWorkWithCounts(context.Context, backend.WorkFilter) ([]*backend.IssueWithCounts, error) {
	return nil, unsupported("GetReadyWorkWithCounts")
}
func (*Store) GetRepoMtime(context.Context, string) (int64, error) {
	return 0, unsupported("GetRepoMtime")
}
func (*Store) GetStaleIssues(context.Context, backend.StaleFilter) ([]*backend.Issue, error) {
	return nil, unsupported("GetStaleIssues")
}
func (*Store) GetStatistics(context.Context) (*backend.Statistics, error) {
	return nil, unsupported("GetStatistics")
}
func (*Store) GetStatisticsNoBlocked(context.Context) (*backend.Statistics, error) {
	return nil, unsupported("GetStatisticsNoBlocked")
}
func (*Store) GetTier1Candidates(context.Context) ([]*backend.CompactionCandidate, error) {
	return nil, unsupported("GetTier1Candidates")
}
func (*Store) GetTier2Candidates(context.Context) ([]*backend.CompactionCandidate, error) {
	return nil, unsupported("GetTier2Candidates")
}
func (*Store) HasRemote(context.Context, string) (bool, error) {
	return false, unsupported("HasRemote")
}
func (*Store) HeartbeatIssue(context.Context, string, string) error {
	return unsupported("HeartbeatIssue")
}
func (*Store) History(context.Context, string) ([]*backend.HistoryEntry, error) {
	return nil, unsupported("History")
}
func (*Store) ImportIssueComment(context.Context, string, string, string, time.Time) (*backend.Comment, error) {
	return nil, unsupported("ImportIssueComment")
}
func (*Store) InitVerifier() (issueops.InitVerifier, error) { return nil, unsupported("InitVerifier") }
func (*Store) IsBlocked(context.Context, string) (bool, []string, error) {
	return false, nil, unsupported("IsBlocked")
}
func (*Store) IsBlockedBatch(context.Context, []string) (map[string]bool, error) {
	return nil, unsupported("IsBlockedBatch")
}
func (*Store) IsInfraTypeCtx(context.Context, backend.IssueType) bool { return false }
func (*Store) IssueClaimer() (issueops.Claimer, error)                { return nil, unsupported("IssueClaimer") }
func (*Store) IssueLifecycle() (issueops.Lifecycle, error)            { return nil, unsupported("IssueLifecycle") }
func (*Store) IssueReader() (issueops.Reader, error)                  { return nil, unsupported("IssueReader") }
func (*Store) IssueRelations() (issueops.Relations, error)            { return nil, unsupported("IssueRelations") }
func (*Store) IterAllDependencyRecords(context.Context) (backend.Iter[backend.Dependency], error) {
	return nil, unsupported("IterAllDependencyRecords")
}
func (*Store) IterAllEventsSince(context.Context, time.Time) (backend.Iter[backend.Event], error) {
	return nil, unsupported("IterAllEventsSince")
}
func (*Store) IterBlockedIssues(context.Context, backend.WorkFilter) (backend.Iter[backend.BlockedIssue], error) {
	return nil, unsupported("IterBlockedIssues")
}
func (*Store) IterDependenciesWithMetadata(context.Context, string) (backend.Iter[backend.IssueWithDependencyMetadata], error) {
	return nil, unsupported("IterDependenciesWithMetadata")
}
func (*Store) IterDependentsWithMetadata(context.Context, string) (backend.Iter[backend.IssueWithDependencyMetadata], error) {
	return nil, unsupported("IterDependentsWithMetadata")
}
func (*Store) IterEvents(context.Context, string, int) (backend.Iter[backend.Event], error) {
	return nil, unsupported("IterEvents")
}
func (*Store) IterIssueComments(context.Context, string) (backend.Iter[backend.Comment], error) {
	return nil, unsupported("IterIssueComments")
}
func (*Store) IterIssues(context.Context, string, backend.IssueFilter) (backend.Iter[backend.Issue], error) {
	return nil, unsupported("IterIssues")
}
func (*Store) IterReadyWork(context.Context, backend.WorkFilter) (backend.Iter[backend.Issue], error) {
	return nil, unsupported("IterReadyWork")
}
func (*Store) IterWisps(context.Context, backend.WispFilter) (backend.Iter[backend.Issue], error) {
	return nil, unsupported("IterWisps")
}
func (*Store) ListBranches(context.Context) ([]string, error) {
	return nil, unsupported("ListBranches")
}
func (*Store) ListFederationPeers(context.Context) ([]*backend.FederationPeer, error) {
	return nil, unsupported("ListFederationPeers")
}
func (*Store) ListRemotes(context.Context) ([]backend.RemoteInfo, error) {
	return nil, unsupported("ListRemotes")
}
func (*Store) ListWisps(context.Context, backend.WispFilter) ([]*backend.Issue, error) {
	return nil, unsupported("ListWisps")
}
func (*Store) Log(context.Context, int) ([]backend.CommitInfo, error) { return nil, unsupported("Log") }
func (*Store) Memories() (memoryops.Memories, error)                  { return nil, unsupported("Memories") }
func (*Store) Merge(context.Context, string) ([]backend.Conflict, error) {
	return nil, unsupported("Merge")
}
func (*Store) MergeMetadata(context.Context, string, string, json.RawMessage, string) error {
	return unsupported("MergeMetadata")
}
func (*Store) MergeSlotAcquire(context.Context, string, string, bool) (*backend.MergeSlotResult, error) {
	return nil, unsupported("MergeSlotAcquire")
}
func (*Store) MergeSlotCheck(context.Context) (*backend.MergeSlotStatus, error) {
	return nil, unsupported("MergeSlotCheck")
}
func (*Store) MergeSlotCreate(context.Context, string) (*backend.Issue, error) {
	return nil, unsupported("MergeSlotCreate")
}
func (*Store) MergeSlotRelease(context.Context, string, string) error {
	return unsupported("MergeSlotRelease")
}
func (*Store) PromoteFromEphemeral(context.Context, string, string) error {
	return unsupported("PromoteFromEphemeral")
}
func (*Store) Pull(context.Context) error { return unsupported("Pull") }
func (*Store) PullFrom(context.Context, string) ([]backend.Conflict, error) {
	return nil, unsupported("PullFrom")
}
func (*Store) PullRemote(context.Context, string) error       { return unsupported("PullRemote") }
func (*Store) Push(context.Context) error                     { return unsupported("Push") }
func (*Store) PushRemote(context.Context, string, bool) error { return unsupported("PushRemote") }
func (*Store) PushTo(context.Context, string) error           { return unsupported("PushTo") }
func (*Store) Querier() (issueops.Querier, error)             { return nil, unsupported("Querier") }
func (*Store) ReadyClaimer() (issueops.ReadyClaimer, error)   { return nil, unsupported("ReadyClaimer") }
func (*Store) ReadyCounter() (issueops.ReadyCounter, error)   { return nil, unsupported("ReadyCounter") }
func (*Store) ReclaimExpiredLeases(context.Context, time.Duration, backend.ReclaimFilter, string) ([]backend.ReclaimedLease, error) {
	return nil, unsupported("ReclaimExpiredLeases")
}
func (*Store) RecordProvenanceEvent(context.Context, backend.ProvenanceEvent) (string, bool, error) {
	return "", false, unsupported("RecordProvenanceEvent")
}
func (*Store) RemoveDependency(context.Context, string, string, string) error {
	return unsupported("RemoveDependency")
}
func (*Store) RemoveDependencyWithOptions(context.Context, string, string, string, backend.DependencyRemoveOptions) error {
	return unsupported("RemoveDependencyWithOptions")
}
func (*Store) RemoveFederationPeer(context.Context, string) error {
	return unsupported("RemoveFederationPeer")
}
func (*Store) RemoveLabel(context.Context, string, string, string) error {
	return unsupported("RemoveLabel")
}
func (*Store) RemoveRemote(context.Context, string) error { return unsupported("RemoveRemote") }
func (*Store) ReopenIssue(context.Context, string, string, string) error {
	return unsupported("ReopenIssue")
}
func (*Store) ResolveConflicts(context.Context, string, string) error {
	return unsupported("ResolveConflicts")
}
func (*Store) RestoreFromSnapshot(context.Context, string) (*backend.IssueSnapshot, error) {
	return nil, unsupported("RestoreFromSnapshot")
}
func (*Store) RunInIssueLifecycleTransaction(context.Context, string, func(backend.IssueLifecycleTransaction) error) error {
	return unsupported("RunInIssueLifecycleTransaction")
}
func (*Store) RunInTransaction(context.Context, string, func(backend.Transaction) error) error {
	return unsupported("RunInTransaction")
}
func (*Store) SearchIssueIDs(context.Context, string, backend.IssueFilter) ([]string, error) {
	return nil, unsupported("SearchIssueIDs")
}
func (*Store) SearchIssues(context.Context, string, backend.IssueFilter) ([]*backend.Issue, error) {
	return nil, unsupported("SearchIssues")
}
func (*Store) SearchIssuesWithCounts(context.Context, string, backend.IssueFilter) ([]*backend.IssueWithCounts, error) {
	return nil, unsupported("SearchIssuesWithCounts")
}
func (*Store) SetConfig(context.Context, string, string) error { return unsupported("SetConfig") }
func (*Store) SetLocalMetadata(context.Context, string, string) error {
	return unsupported("SetLocalMetadata")
}
func (*Store) SetMetadata(context.Context, string, string) error { return unsupported("SetMetadata") }
func (*Store) SetRepoMtime(context.Context, string, string, int64) error {
	return unsupported("SetRepoMtime")
}
func (*Store) SlotClear(context.Context, string, string, string) error {
	return unsupported("SlotClear")
}
func (*Store) SlotGet(context.Context, string, string) (string, error) {
	return "", unsupported("SlotGet")
}
func (*Store) SlotSet(context.Context, string, string, string, string) error {
	return unsupported("SlotSet")
}
func (*Store) SnapshotIssue(context.Context, string, int) error { return unsupported("SnapshotIssue") }
func (*Store) StatsReporter() (issueops.StatsReporter, error) {
	return nil, unsupported("StatsReporter")
}
func (*Store) Status(context.Context) (*backend.VCStatus, error) { return nil, unsupported("Status") }
func (*Store) Sweeper() (issueops.Sweeper, error)                { return nil, unsupported("Sweeper") }
func (*Store) Sync(context.Context, string, string) (*backend.SyncResult, error) {
	return nil, unsupported("Sync")
}
func (*Store) SyncStatus(context.Context, string) (*backend.SyncStatus, error) {
	return nil, unsupported("SyncStatus")
}
func (*Store) TreeWalker() (issueops.TreeWalker, error) { return nil, unsupported("TreeWalker") }
func (*Store) UnclaimIssue(context.Context, string, string, bool) error {
	return unsupported("UnclaimIssue")
}
func (*Store) UnclaimIssueIfAssignee(context.Context, string, string, string) error {
	return unsupported("UnclaimIssueIfAssignee")
}
func (*Store) UpdateIssue(context.Context, string, map[string]interface{}, string) error {
	return unsupported("UpdateIssue")
}
func (*Store) UpdateIssueChecked(context.Context, string, map[string]interface{}, string, backend.UpdateIssueOptions) error {
	return unsupported("UpdateIssueChecked")
}
func (*Store) UpdateIssueID(context.Context, string, string, *backend.Issue, string) error {
	return unsupported("UpdateIssueID")
}
func (*Store) UpdateIssueType(context.Context, string, string, string) error {
	return unsupported("UpdateIssueType")
}
func (*Store) VersionReconciler() (issueops.VersionReconciler, error) {
	return nil, unsupported("VersionReconciler")
}
func (*Store) WorkspaceConfig() (issueops.WorkspaceConfig, error) {
	return nil, unsupported("WorkspaceConfig")
}
